# Generated by Django 5.2.1 on 2025-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BNB', 'BNB'), ('LTC', 'Litecoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin')], max_length=10)),
                ('network', models.CharField(choices=[('BSC20', 'Binance Smart Chain (BEP-20)'), ('LTC', 'Litecoin'), ('ERC20', 'Ethereum (ERC-20)'), ('Base', 'Base'), ('Arbitrum', 'Arbitrum'), ('TRC20', 'Tron (TRC-20)'), ('Aptos', 'Aptos')], max_length=10)),
                ('address', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
