# Generated by Django 5.2.1 on 2025-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptowallet',
            name='currency',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='crypto',
            field=models.CharField(choices=[('BNB', 'BNB'), ('LTC', 'LTC'), ('ETH', 'ETH'), ('USDT', 'USDT'), ('USDC', 'USDC')], default='USDT', max_length=10, verbose_name='Криптовалюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адреса гаманця'),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='network',
            field=models.CharField(choices=[('BSC', 'Binance Smart Chain (BSC)'), ('ERC20', 'Ethereum (ERC20)'), ('BASE', 'Base'), ('ARBITRUM', 'Arbitrum'), ('TRC20', 'TRON (TRC20)'), ('APTOS', 'Aptos')], max_length=20, verbose_name='Мережа'),
        ),
    ]
