# Generated by Django 5.2.1 on 2025-05-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_cryptowallet_currency_cryptowallet_crypto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='crypto',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USDC', 'USDC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('LTC', 'LTC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.network'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('crypto', 'network')},
        ),
        migrations.RemoveField(
            model_name='cryptowallet',
            name='address',
        ),
    ]
