# Generated by Django 5.2.1 on 2025-05-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_network_alter_cryptowallet_crypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
