# Generated by Django 5.2.1 on 2025-05-29 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address'),
        ('payment', '0003_network_alter_cryptowallet_crypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.cryptowallet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('crypto', 'Криптовалюта'), ('cash', 'Готівкою при отриманні')], max_length=20),
        ),
    ]
